export enum EUserEvents {
    USER_SIGNUP_INITIATED = "USER_SIGNUP_INITIATED",
    USER_SIGNUP_COMPLETED = "USER_SIGNUP_COMPLETED",
}

export enum ECourseEvents {
    COURSE_CREATED = "COURSE_CREATED",
    COURSE_ANNOUNCEMENT_CREATED = "COURSE_ANNOUNCEMENT_CREATED",
    COURSE_VERIFICATION_UPDATED = "COURSE_VERIFICATION_UPDATED",
}

export enum EChatEvents {
    CHAT_MESSAGE_CREATED = "CHAT_MESSAGE_CREATED",
    CHAT_MESSAGE_UPDATED = "CHAT_MESSAGE_UPDATED",
    CHAT_MESSAGE_DELETED = "CHAT_MESSAGE_DELETED",
}

export type IEventEmitterOnFunction = (
    event: string | symbol,
    listener: (...args: any[]) => void
) => any;
