export enum EModels {
    USER = "USER",
    CHAT = "CHAT",
    COURSE = "COURSE",
    INSTRUCTOR = "INSTRUCTORS",
    LOCATION = "LOCATION",
    MAILING_LIST_SUBSCRIBER = "MAILING_LIST_SUBSCRIBER",
    SCHOOL_OFFICIAL = "SCHOOL_OFFICIAL",
    SCHOOL = "SCHOOL",
    STUDENT = "STUDENT",
}
